# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20160519_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSelection',
            new_name='Selection',
        ),
    ]
