# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignmentId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('assignmentName', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('addTime', models.DateTimeField()),
                ('deadlineTime', models.DateTimeField(null=True)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submissionId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('SubmissionTime', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('assignmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Assignments')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users')),
            ],
        ),
    ]
