# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='assignmentName',
            new_name='name',
        ),
    ]
