# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('userType', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=10)),
            ],
        ),
    ]
