# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='userName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='userType',
            new_name='type',
        ),
    ]
